apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello12345-deployment
  namespace: deeksha
  labels:
    app:  hello12345
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  hello12345
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: hello12345
    spec:
      initContainers:
      - name: init-setup
        image: busybox:latest
        command: ['sh', '-c', 'ls; pwd; sleep 10']
        envFrom:
        - configMapRef:
            name: hello12345-deployment
      containers:
      - name: hello12345
        image: deekshamaddineni/dee:latest
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000   # Corrected port to match the containerPort
          initialDelaySeconds: 8
          periodSeconds: 10
          failureThreshold: 3  # Corrected field name
          successThreshold: 1  # Corrected field name
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000   # Corrected port to match the containerPort
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
        - name: hello12345-deployment
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: hello12345-deployment
