apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdocker-app-deployment 
  labels:
    app: dotnetdocker-app
  namespace: deeksha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetdocker-app
  template:
    metadata:
      labels:
        app: dotnetdocker-app
    spec:
      containers:
      - name: dotnetdocker-app
        image: deekshamaddineni/newdotnet-d-app:latest
        ports:
        - containerPort: 5000