apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: newdotnet-d-app-role
  namespace: de
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]