apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: newdotnet-d-app-rolebinding
  namespace: redblue
subjects:
- kind: ServiceAccount
  name: newdotnet-d-app-serviceaccount
  namespace: redblue
roleRef:
  kind: Role
  name: newdotnet-d-app-role
  apiGroup: rbac.authorization.k8s.io