apiVersion: v1
kind: Service
metadata:
  name: newdotnet-d-app-deployment 
  namespace: de
spec:
  selector:
    app: newdotnet-d-app
    type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000