apiVersion: v1
kind: Service
metadata:
  name: assignnew-1.0.1-deployment 
  namespace: abcd
spec:
  selector:
    app: assignnew:1.0.1
    type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000